name: gg_list
description: GgList - Effectively manage native and nonative 1d and 2d data
version: 1.1.0
repository: https://github.com/inlavigo/gg_list

environment:
  sdk: ">=3.2.0 <4.0.0"

dev_dependencies:
  args: ^2.4.2
  coverage: ^1.7.2
  lints: ^3.0.0
  pana: ^0.21.45
  test: ^1.24.0
