name: gg_list
description: GgList - Automatically chose the right native list type
version: 1.0.1
repository: https://github.com/inlavigo/gg_list

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  args: ^2.4.2
  coverage: ^1.7.2
  lints: ^3.0.0
  test: ^1.24.0
