name: gg_list
description: GgList - Effectively manage native and nonative 1d and 2d data
version: 2.0.1
repository: https://github.com/inlavigo/gg_list

environment:
  sdk: ">=3.2.0 <4.0.0"

dev_dependencies:
  args: ^2.4.2
  coverage: ^1.7.2
  gg_capture_print: ^1.0.2
  lints: ^3.0.0
  test: ^1.24.0